# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python Automation (Selenium + Pytest)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Install firefox and firefox driver
      run: |
        GECKODRIVER_VERSION="0.34.0"  # Specify the desired version
        wget https://github.com/mozilla/geckodriver/releases/download/v${GECKODRIVER_VERSION}/geckodriver-v${GECKODRIVER_VERSION}-linux64.tar.gz
        tar -xvzf geckodriver-v${GECKODRIVER_VERSION}-linux64.tar.gz
        chmod +x geckodriver
        mv geckodriver /usr/local/bin/geckodriver
    - name: Run test with pytest
      run: |
        pytest
